Favorful/Models/Treat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Favorful.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }

    [Display(Name = "Customer Rating (out of 5)")]
    [Range(1,5)]
    public int CustomerRating { get; set; }

    public int Price { get; set; }

    public string Description { get; set; }

    [Display(Name = "Current Stock")]
    public int CurrentStock { get; set; }
    
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }
}

Favorful/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Favorful.Models;
using System.Collections.Generic;
using System.Linq;

namespace Favorful.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly FavorfulContext _db;

    public FlavorsController(FavorfulContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }
    
    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat(){ TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Favorful/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Favorful.Models;

namespace Favorful.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly FavorfulContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, FavorfulContext db)
    {
      _userManager = userManager;
      _db = db;
    }

     public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userTreats = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).ToList();
        return View(userTreats);
    }

     public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        _db.SaveChanges();
        if (FlavorId != 0)
        {
            _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Type");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Type");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
      _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Favorful/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model Favorful.Models.Treat

<h1>FLAVOR ASSIGNMENT</h1>
<hr />
<h2>Give @Html.DisplayFor(model => model.Name)  a flavor</h2>

@if (Enumerable.Count(ViewBag.FlavorId) != 0)
{
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select Flavor")
    <br>
    @Html.DropDownList("FlavorId")
    <br>
    <br>
    <input type="submit" value="Save">
  }
}
else
{
  <h4>This treat currently doesn't have any flavors</h4>
  <p>@Html.ActionLink("Add new Flavor", "Create", "Flavors", null, new {@class="button"})</p>
}
<hr />
<p>@Html.ActionLink("Back to treat list", "Index", "Treats", null, new {@class="button"})</p>

Favorful/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Favorful.Models.Treat

<h1>ADD TREAT</h1>
<hr/>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    <br>
    @Html.TextBoxFor(model => model.Name, new {@required="required"})
    <br>
    <br>
    @Html.LabelFor(model => model.CustomerRating)
    <br>
    @Html.TextBoxFor(model => model.CustomerRating, new {@type="number", @min=1, @max=5})
    <br>
    <br>
    @Html.LabelFor(model => model.Price)
    <br>
    @Html.TextBoxFor(model => model.Price, new {@type="number", @min=1})
    <br>
    <br>
    @Html.LabelFor(model => model.Description)
    <br>
    @Html.TextBoxFor(model => model.Description)
    <br>
    <br>
    @Html.LabelFor(model => model.CurrentStock)
    <br>
    @Html.TextBoxFor(model => model.CurrentStock, new {@type="number", @min=0, @required="required"})
    <br>
    <br>
    <input type="submit" value="Add new Treat" class="btn btn-default" />
}
<br>
<p>@Html.ActionLink("Show all Treats", "Index")</p>

Favorful/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Favorful.Models.Treat

<h1>REMOVE TREAT</h1>
<hr />

<h2>Are you sure you want to delete this treat?</h2>
<br>
<p><strong>@Html.DisplayNameFor(model => model.Name):</strong> @Html.DisplayFor(model => model.Name)</p>
<br>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="delete">
}
<br>
<hr />
<p>@Html.ActionLink("Back to treat list", "Index", "Treats", null, new {@class="button"})</p>

Favorful/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model Favorful.Models.Treat

<h1>TREAT INFOMRATION</h1>
<hr />

<h2>@Html.DisplayFor(model => model.Name)</h2>

<p class="blocktext"><strong>@Html.DisplayNameFor(model => model.CustomerRating):</strong> @Html.DisplayFor(model => model.CustomerRating)</p>
<p class="blocktext"><strong>@Html.DisplayNameFor(model => model.Price):</strong> @Html.DisplayFor(model => model.Price)</p>
<p class="blocktext"><strong>@Html.DisplayNameFor(model => model.Description):</strong> @Html.DisplayFor(model => model.Description)</p>
<p class="blocktext"><strong>@Html.DisplayNameFor(model => model.CurrentStock):</strong> @Html.DisplayFor(model => model.CurrentStock)</p>
<hr />
@if (@Model.JoinEntities.Count == 0)
{
  <h2>This treat doesn't have any flavors</h2>
}
else
{
  <h2>Treat Flavors @Html.DisplayFor(model => model.Name):</h2>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Flavor.Type</li>
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Remove Flavor" class="delete-object"/>
      }
    }
  </ul>
}
<hr />
<p>@Html.ActionLink("Assign to Flavor", "AddFlavor", new { id = Model.TreatId}, new {@class="button"})</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId}, new {@class="button"})</p>
<p>@Html.ActionLink("Remove Treat", "Delete", new { id = Model.TreatId}, new {@class="button"})</p>
<p>@Html.ActionLink("Back to Treat list", "Index", "Treats", null, new {@class="button"})</p>

Favorful/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Favorful.Models.Treat

<h1>EDIT TREAT</h1>
<hr />

<h2>@Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  <br>
  @Html.EditorFor(model => model.Name)
  <br>
  <br>
  @Html.LabelFor(model => model.CustomerRating)
  <br>
  @Html.EditorFor(model => model.CustomerRating)
  <br>
  <br>
  @Html.LabelFor(model => model.Price)
  <br>
  @Html.EditorFor(model => model.Price)
  <br>
  <br>
  @Html.LabelFor(model => model.Description)
  <br>
  @Html.EditorFor(model => model.Description)
  <br>
  <br>
  @Html.LabelFor(model => model.CurrentStock)
  <br>
  @Html.EditorFor(model => model.CurrentStock)
  <br>
  <br>
  @if (Enumerable.Count(ViewBag.FlavorId) != 0)
  {
    @Html.Label("Assign Flavor")
    <br>
    @Html.DropDownList("FlavorId")
    <br>
    <br>
  }
  <input type="submit" value="Save">
  <br>
  <br>
}
<hr />
<p>@Html.ActionLink("Back to Treat List", "Index", "Treats", null, new {@class="button"})</p>

Favorful/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Favorful.Models;
@model IEnumerable<Favorful.Models.Treat>

<h1>TREATS</h1>
<hr/>

@if (Model.Any())
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
} 
else
{
  <h3>No treats have been added yet</h3>
}
<p>@Html.ActionLink("Add new Treat", "Create")</p>
<hr/>